### ISSUE TITLE
Key latency delay experimental code.

### ISSUE THREAD

**Issue by louis-barman** [amowry/warbl#10]
Just to let you know that I have been playing with adding key latency delay to the code using a different technique. I have read what you wrote in the forum here: https://warbl.xyz/phpbb/viewtopic.php?p=838#p838 and agree with it completely. It is only useful to get rid of ultra short transient notes. 

I can make the code available in my GitHub fork on request.

**Comment by amowry** [comment]
That's a nice way to add a key delay-- I had been thinking of adding a delay in the code where a new note is sent, but it hadn't occurred to me to debounce the tone holes individually. That avoids a lot of complexity in terms of maintaining the order of NoteOn/NoteOff commands.

**Comment by louis-barman** [comment]
**Please note:** this only required for some sounds synths especially fluidsynth that has a hard attack at the start of every `note on` received. Sound synths that model a real wind instrument are not as sensitive to ultra short transient notes.

There is a another use case for this where people want to use the warbl with a musical notation app and so don't want any  transient notes at all.

Yes it is working very well for me I have the following  value harded code in my fork see (https://github.com/louis-barman/warbl/tree/wip/debounce)

```
// Note // LB With a value of 30 it just starts getting noticeable with 5 most but not all spurious transient notes are suppressed
#define TONEHOLE_DEBOUNCE_COUNTER 8 // Set to 1 for off
```

I think with a value of 30 I just began noticing a latency delay. 
Also (if i remember correctly) a value of 16 would only just filter out the fasted trill I could play. so i chose 8 being half this value.

Regarding the config UI we could add new field called "filter transient notes" or perhaps called "suppress ultra short notes".

I was thinking of having four values "OFF", "LOW (recommend)", "MEDIUM" and "HIGH" but now I think a field in mSec is better. Provided we stated what the recommend setting should be something like:

**filter transient notes [NUMBER_FIELD]   seSec** with the tool tilp "value in milliseconds - 0 for OFF, 8 recommend ,100 max"

Once Andrew has agreed in principle that we want to go ahead with this and how we should implement it. I would then do a pull request for this code change for the Warbl code only.

Also a technical question regarding the WARBL: how often do you read the finger holes in mSec and is there any jitter on this time. Same question for the breath pressure how often do you read the breath pressure and is it synchronised to reading the finger hole readings.

**Comment by amowry** [comment]
I agree this would be useful, for all the reasons you mentioned. I also agree that a mSec entry field/slider would be best, as then users can understand in concrete terms exactly what the setting does. I expect that we may not end up needing all of the jump/drop settings exposed in the UI, so I might be able to repurpose one of those.

I read the finger holes about once every 1 ms. I'm sure there is some jitter because although it's tied to the ADC interrupt I think there's some variability in the time it takes for the conversions. I haven't measured the jitter but I would guess it's not more than 100 us or so. W read the pressure sensor in series with all the other sensors, so they are synchoronized. 1 ms is also the rated minimum response time for the pressure sensor, so we're reading it at the highest meaningful rate.

**Comment by amowry** [comment]
I tested the key delay and it seems to work fine. I think we'll need some version of the jump/drop back, though, because adding enough key delay to play a similar role adds a lot of latency. If you want to make the key delay work with the existing jump/drop, then I can refine that part after incorporating your additions.

**Comment by amowry** [comment]
I'm adding this in the 2.1 release.
