### ISSUE TITLE
Ability to set the midi channel for an instrument

### ISSUE THREAD

**Issue by bxjx** [amowry/warbl#2]
I've just received a warbl and I love it! So fun controlling soft synths and even my modular from it. Amazing work!

Feature request: I'd love if it could be possible to set different midi channels per instrument. This would make it easier to set up dedicated synths per instrument and then easily move between them using the buttons.

It looks like the channel is currently hardcoded: https://github.com/amowry/warbl/blob/e025d56aa14ecca716489b62a9d0c4bed66edca5/WARBL_1.8/functions.ino#L777.

Would this be a big job to change? 

I'd be happy to have a shot but I have no time till November.

Thanks!
Bridger

**Comment by amowry** [comment]
I'm glad you're enjoying WARBL, and thanks for the suggestion! I've considered doing this, but I wasn't sure how many people would use it, and I didn't want to complicate things for users unnecessarily, but I may at least be able to make you a custom version at some point that. The easiest way would be to just have it use the instrument number as the MIDI channel, so instrument 1 would use channel 1, etc. You wouldn't be able to change those without uploading different firmware, but it might serve your purpose. Otherwise we'd need to add it to the user interface, store it in EEPROM, for when the device is restarted, etc. If you'd like to try the simpler idea let me know, and I'd be happy to make a version where it uses the instrument number as the MIDI channel.

**Comment by bxjx** [comment]
That's a great solution and would perfectly for me!

A custom version would be wonderful 😍 

For what it's worth, your solution could make updating the interface easier as I guess you could just have a toggle (off by default) that was something like `Use the instrument number as the midi channel` and perhaps you'd only have to store the value of that toggle in the EEPROM?

Thanks @amowry !

**Comment by amowry** [comment]
That's a good idea-- I may add that to the next release version. In the meantime, here's one where it always uses the instrument number for the MIDI channel: 

[https://github.com/amowry/warbl/blob/master/WARBL_1.8_multiple_MIDI_channels.ino.hex](url)

There are instructions on the WARBL site for uploading new firmware, but let me know if you have any questions.

**Comment by bxjx** [comment]
Will have a shot and report back! Thanks so much for the quick turnaround!

**Comment by bxjx** [comment]
Worked perfectly! Nice one! I'll leave with you as to whether you want to close the issue. Thanks @amowry !

**Comment by amowry** [comment]
Great, I'm glad it's working!
