### ISSUE TITLE
No hysteresis when overblowing to get the top octave

### ISSUE THREAD

**Issue by louis-barman** [amowry/warbl#6]
From the forum https://warbl.xyz/phpbb/viewtopic.php?f=6&t=222

I am having trouble getting the overblowing working properly for the top register as it keeps dropping to the lower register when I don't want it to. I have tried fiddling with the settings for this with no luck. However I realise that there is an easy software fix and that is to implement hysteresis when overblowing, this is something that a real whistle does naturally -- you initially have to blow quite hard to get the top register but once there it tends to stay in that register even if you back of the pressure. in fact on my whistle i have to back off the pressure quite a bit before it drops back down to the lower octave. I am a programmer and an electronic engineer by training and also the author of PianoBooster so I might have a go at trying to fix this issue myself.

**Comment by louis-barman** [comment]
I have just submit my suggested fix you can view it and test in the branch `wip/hysteresis` available here https://github.com/louis-barman/warbl/tree/wip/hysteresis

I am using and recommend using qsynth  https://sourceforge.net/projects/qsynth/  and BreathExperssion soundfont  https://github.com/louis-barman/breath-expression-soundfont with  Harmon Mute Trumpet as the instrumment. and this is the config that I am using: [WARBL_Preset_for_hysteresis_testing.zip](https://github.com/amowry/warbl/files/6807754/WARBL_Preset_for_hysteresis_testing.zip)


Set `buttonPrefs[mode][7][4]` to a value between 0 to 100 for no hysteresis to 100% hysteresis.

I have found this change works quite well for me with 100% hysteresis it will jump to the top octave at  125% of `upperBound` drop back down  when `sensorValue2` drops  to 25% of  `upperBound`. I haven't decided on the exact value to use yet but i am testing with 60% hysteresis

I have disabled /commented out jumping and dropping code for now as there are thing in it I need to investigate. I have also temporarily disabled the very high top D as that was casing me problems as well.

This code at the moment is not ready for PR (Pull Request) but as discustion as the right way to go.

**Comment by amowry** [comment]
I'd want to test to make sure this works with the "expression" pitch bend if you haven't already done that, as it is reliant on knowing both the current state and the upper/lower pressure bounds for the current note. I'm not sure offhand how it will respond if the lower bound is dynamic because of the hysteresis. We'd also need to integrate it with the jump/drop, as you mentioned, but I don't think that would be too much of an issue because of the delays that allow the pressure to stabilize after a jump or drop occurs.

**Comment by louis-barman** [comment]
Regarding the UI change to implement this I have implement as percentage ranging from 0% (for off) to %100 max. I suggest that a new overblowing hysteresis is added to the advanced register control settings called "overblowing hysteresis" with a default of 60%.

A value of 60% is working very well for me. With a value of 60% it for me it feels very natural and responds like a whistle without needing any change to my way of whistle playing when switching to and from the warbl (previously I was needing to blow extra hard when over blowing on the wabrl to prevent me accidentally dropping down an octave.)

I did not get on with "expression" pitch bend so have disabled it. (Probably because I don't have an iPhone and and may not work well on fluidsynth or ZynAddSubFx). But I will compare how it behaves now and also after my changes.

Once Andrew has agreed in principle that we want to go ahead and add this feature and roughly how we should implement it. I would then do a pull request for this code change for the Warbl code only for him to review.

**Comment by amowry** [comment]
The hysteresis seems to work well for me too. It does break the expression pitch bend, though, so that would need to be fixed. Currently, if you set the pitch bend to the max, then play a note in the second register, then slowly reduce the pressure, the pitch will drop for a bit and then go sharp again before the note drops to the first register. It may be as simple as using your newly calculated lower bound in the pitch calculations, or possibly just putting a cap on the pitch bend. The main purpose of the expression was to add realism for bagpipers, where reducing the bag pressure causes the note to go flat. I find it also works well for breath vibrato, though.

**Comment by amowry** [comment]
I didn't end up adding this one because of the complexity of getting it to work with the pitch expression.
